### ISSUE TITLE
Advantages over vim-plug?

### ISSUE THREAD

**Issue by iology** [VividVim/Vivid.vim#2]
https://github.com/junegunn/vim-plug

**Comment by axvr** [comment]
NOTE: This project is unmaintained. 

I had discovered Vim-Plug about three weeks ago and I do currently plan on switching to it in the next couple of weeks. The original goal of Vivid was asynchronous downloads, for both Vim and Neovim (it appears that Vim-Plug only does the asynchronous downloads and install for Neovim). Vivid was going to achieve this goal by relaying the processor intensive tasks to Python rather than using the famously slow VimL. TL;DR: The main speed change between the two ,would be for regular Vim.

If I encounter any problems with Vim-Plug, I will probably submit changes upstream. If I cannot, Vivid will probably become maintained again and hopefully functional.
